//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAWcfService
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [Serializable]
    [DataContract]
    
    public partial class FileType
    {
    	[DataMember]
        public int FileTypeID { get; set; }
    	[DataMember]
        public string TypeName { get; set; }
    	[DataMember]
        public Nullable<int> ParentID { get; set; }
    }
}
