//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAWcfService
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [Serializable]
    [DataContract]
    [KnownType(typeof(Course))]
    [KnownType(typeof(Works))]
    
    public partial class Periods
    {
        public Periods()
        {
            this.Works = new HashSet<Works>();
        }
    
    	[DataMember]
        public long PeriodID { get; set; }
    	[DataMember]
        public string PeriodTitle { get; set; }
    	[DataMember]
        public string PeriodCode { get; set; }
    	[DataMember]
        public Nullable<long> CourseID { get; set; }
    	[DataMember]
        public string Require { get; set; }
    	[DataMember]
        public Nullable<int> WorksTypeID { get; set; }
    	[DataMember]
        public Nullable<int> Number { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> StartSubmit { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> EndSubmit { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> StartScore { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> EndScore { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> StartPublic { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> EndPublic { get; set; }
    	[DataMember]
        public Nullable<long> CreatedBy { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> Created { get; set; }
    	[DataMember]
        public Nullable<long> ModifiedBy { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> Modified { get; set; }
    	[DataMember]
        public Nullable<int> Flag { get; set; }
    
    	[DataMember]
        public virtual Course Course { get; set; }
    	[DataMember]
        public virtual ICollection<Works> Works { get; set; }
    }
}
