//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAWcfService
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [Serializable]
    [DataContract]
    [KnownType(typeof(UserWorks))]
    
    public partial class User
    {
        public User()
        {
            this.UserWorks = new HashSet<UserWorks>();
        }
    
    	[DataMember]
        public long UserID { get; set; }
    	[DataMember]
        public string Account { get; set; }
    	[DataMember]
        public string Name { get; set; }
    	[DataMember]
        public string IDCard { get; set; }
    	[DataMember]
        public Nullable<bool> Sex { get; set; }
    	[DataMember]
        public string Telephone { get; set; }
    	[DataMember]
        public string Email { get; set; }
    	[DataMember]
        public string Duty { get; set; }
    	[DataMember]
        public string ProfessionalTitle { get; set; }
    	[DataMember]
        public string Department { get; set; }
    	[DataMember]
        public string Major { get; set; }
    	[DataMember]
        public string Class { get; set; }
    	[DataMember]
        public string Grade { get; set; }
    	[DataMember]
        public Nullable<int> RoleID { get; set; }
    	[DataMember]
        public Nullable<int> DegreeID { get; set; }
    	[DataMember]
        public Nullable<int> SchoolID { get; set; }
    	[DataMember]
        public Nullable<long> CreatedBy { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> Created { get; set; }
    	[DataMember]
        public Nullable<long> ModifiedBy { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> Modified { get; set; }
    	[DataMember]
        public Nullable<int> StateID { get; set; }
    	[DataMember]
        public Nullable<long> ApprovedBy { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> Approved { get; set; }
    	[DataMember]
        public Nullable<long> Flag { get; set; }
    	[DataMember]
        public string AppPwd { get; set; }
    	[DataMember]
        public string AppUserScore { get; set; }
    
    	[DataMember]
        public virtual ICollection<UserWorks> UserWorks { get; set; }
    }
}
