//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAWcfService
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [Serializable]
    [DataContract]
    [KnownType(typeof(User))]
    [KnownType(typeof(Works))]
    
    public partial class UserWorks
    {
    	[DataMember]
        public long UserWorksID { get; set; }
    	[DataMember]
        public Nullable<long> UserID { get; set; }
    	[DataMember]
        public Nullable<long> WorksID { get; set; }
    	[DataMember]
        public Nullable<int> Relationship { get; set; }
    	[DataMember]
        public Nullable<int> Flag { get; set; }
    
    	[DataMember]
        public virtual User User { get; set; }
    	[DataMember]
        public virtual Works Works { get; set; }
    }
}
