//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAWcfService
{
    using System;
    using System.Data.Entity.Core.Objects;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VAExtensionWorks : DbContext
    {
    	public VAExtensionWorks()
            : this(false) { }
    
        public VAExtensionWorks(bool proxyCreationEnabled)
            : base("name=VAExtensionWorks")
        {
    		        this.Configuration.ProxyCreationEnabled = proxyCreationEnabled;
        }
    	
        public VAExtensionWorks(string connectionString)
          : this(connectionString, false) { }
    	  
        public VAExtensionWorks(string connectionString, bool proxyCreationEnabled)
            : base(connectionString)
        {
    		        this.Configuration.ProxyCreationEnabled = proxyCreationEnabled;
        }	
    	
        public ObjectContext ObjectContext
        {
          get { return ((IObjectContextAdapter)this).ObjectContext; }
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FileType> FileType { get; set; }
        public virtual DbSet<Works> Works { get; set; }
        public virtual DbSet<WorksFile> WorksFile { get; set; }
        public virtual DbSet<WorksType> WorksType { get; set; }
        public virtual DbSet<Course> Course { get; set; }
        public virtual DbSet<Periods> Periods { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserWorks> UserWorks { get; set; }
        public virtual DbSet<Favorites> Favorites { get; set; }
        public virtual DbSet<FavoriteWorks> FavoriteWorks { get; set; }
        public virtual DbSet<CSMyWorks> CSMyWorks { get; set; }
    }
}
