//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAWcfService
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [Serializable]
    [DataContract]
    [KnownType(typeof(WorksFile))]
    [KnownType(typeof(Periods))]
    [KnownType(typeof(UserWorks))]
    
    public partial class Works
    {
        public Works()
        {
            this.WorksFile = new HashSet<WorksFile>();
            this.UserWorks = new HashSet<UserWorks>();
        }
    
    	[DataMember]
        public long WorksID { get; set; }
    	[DataMember]
        public Nullable<long> PeriodID { get; set; }
    	[DataMember]
        public string WorksName { get; set; }
    	[DataMember]
        public string TeamName { get; set; }
    	[DataMember]
        public Nullable<int> WorksTypeID { get; set; }
    	[DataMember]
        public string WorksCode { get; set; }
    	[DataMember]
        public Nullable<int> OrgID { get; set; }
    	[DataMember]
        public Nullable<int> IsSample { get; set; }
    	[DataMember]
        public string Comment { get; set; }
    	[DataMember]
        public string Profile { get; set; }
    	[DataMember]
        public string SubmitProfile { get; set; }
    	[DataMember]
        public string Suggestion { get; set; }
    	[DataMember]
        public string InstallationGuide { get; set; }
    	[DataMember]
        public string DesignIdeas { get; set; }
    	[DataMember]
        public string KeyPoints { get; set; }
    	[DataMember]
        public string SelfAssessment { get; set; }
    	[DataMember]
        public string DemoURL { get; set; }
    	[DataMember]
        public string BackReason { get; set; }
    	[DataMember]
        public Nullable<float> Score { get; set; }
    	[DataMember]
        public Nullable<long> CreatedBy { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> Created { get; set; }
    	[DataMember]
        public Nullable<long> ModifiedBy { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> Modified { get; set; }
    	[DataMember]
        public Nullable<int> AllotTimes { get; set; }
    	[DataMember]
        public Nullable<int> WorksState { get; set; }
    	[DataMember]
        public Nullable<long> Flag { get; set; }
    	[DataMember]
        public Nullable<long> DomainID { get; set; }
    	[DataMember]
        public string Hits { get; set; }
    
    	[DataMember]
        public virtual ICollection<WorksFile> WorksFile { get; set; }
    	[DataMember]
        public virtual Periods Periods { get; set; }
    	[DataMember]
        public virtual ICollection<UserWorks> UserWorks { get; set; }
    }
}
