//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorksShowDll
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSMyWorks
    {
        public long WorksID { get; set; }
        public string WorksName { get; set; }
        public string CourseName { get; set; }
        public string PeriodTitle { get; set; }
        public string WorksTypeName { get; set; }
        public string StateName { get; set; }
        public Nullable<float> Score { get; set; }
        public Nullable<int> Relationship { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<long> PeriodID { get; set; }
        public Nullable<int> WorksTypeID { get; set; }
        public Nullable<long> UserWorksID { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<long> CourseID { get; set; }
        public Nullable<long> DomainID { get; set; }
        public string WorksCode { get; set; }
        public string DesignIdeas { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string Hits { get; set; }
    }
}
