//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorksShowDll
{
    using System;
    using System.Collections.Generic;
    
    public partial class FavoriteWorks
    {
        public long UserID { get; set; }
        public Nullable<long> DomainID { get; set; }
        public Nullable<long> WorksID { get; set; }
        public string WorksName { get; set; }
        public Nullable<long> AuthorID { get; set; }
        public string AuthorName { get; set; }
    }
}
