//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorksShowDll
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favorites
    {
        public long UserID { get; set; }
        public long ItemID { get; set; }
        public long DomainID { get; set; }
        public Nullable<System.DateTime> FavDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> Flag { get; set; }
    }
}
